import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';

const Dashboard: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <div className='main_wrapper'>
      <Head>
        <title>UniqueHub | Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/svg/site_logo.svg' />
      </Head>

      <div className='container_wrapper'></div>
    </div>
  );
};

export default Dashboard;
