import type { NextPage } from 'next';
import Head from 'next/head';
import AuthHeader from '@components/Auth/Header';
import LoginComponent from '@components/Auth/Login';
import Footer from '@components/Footer';

const Home: NextPage = () => {
  return (
    <div className='main_wrapper'>
      <Head>
        <title>UniqueHub | Login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/svg/site_logo.svg' />
      </Head>

      <div className='container_wrapper'>
        <AuthHeader url='/register' text='Register Now' />
        <LoginComponent />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
