import type { NextPage } from 'next';
import Head from 'next/head';
import AuthHeader from '../components/Auth/Header';
import RegisterComponent from '@components/Auth/Register';
import Footer from '@components/Footer';
import PageSpinner from '@components/Utility/PageSpinner';
import { useEffect, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();
  const { data: session, status } = useSession();
  const [loading, setLoading] = useState(true);

  /** Authentication Check */
  useEffect(() => {
    if (status !== 'loading' && session) {
      router.push('/dashboard');
    }
    if (status !== 'loading' && status == 'unauthenticated') {
      setLoading(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [session, status]);

  /** Spinner While Authentication Check */
  if (loading) return <PageSpinner />;

  return (
    <div className='main_wrapper'>
      <Head>
        <title>Register</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/web_icon.svg' />
      </Head>

      <div style={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
        <AuthHeader url='/' text='Login Now' />
        <RegisterComponent />
        <Footer />
      </div>
    </div>
  );
};

export default Home;
